### ISSUE TITLE
Problem with loading templates.

### ISSUE THREAD

**Issue by Sinled** [ember-cli/ember-resolver#103]
It seems loading broken again?

May be i am doing something wrong but it isn't working for me.
here is test app:
https://github.com/Sinled/ember-tests/tree/master/test-loading/app

i have 
```
application.loading
posts.loading
```
templates but none of them are actually loading
```
   Ember      : 1.13.5
   ember-cli  : 1.13.6
```

**Comment by teddyzeenny** [comment]
You need to remove the application route's [loading action](https://github.com/Sinled/ember-tests/blob/5fe3dacc29dcd276ee896406024ea3f6fcd1035c/test-loading/app/routes/application.js#L5-L7).

**Comment by Sinled** [comment]
@teddyzeenny yes, it is working without loading action, thats is strange, what should i do if i also need to catch loading event in route?

**Comment by stefanpenner** [comment]
Call super

**Comment by Sinled** [comment]
@teddyzeenny @stefanpenner Thanks!
