### ISSUE TITLE
When variable and helper shares the same name, the helper always wins

### ISSUE THREAD

**Issue by tim-evans** [ember-cli/ember-resolver#108]
Calling helpers should be unambiguous. If a template has a hash or positional parameter, it should call the helper, otherwise, it should lookup the variable.

See http://ember-twiddle.com/b3b796e77b72d2e6c816

Tracking issue https://github.com/paddle8/ember-document-title/issues/20

**Comment by stefanpenner** [comment]
I'm not sure this is an ember-resolver issue, it would seem it has insufficient context to make this choice but ember proper does.

**Comment by stefanpenner** [comment]
I suspect the change was allowing dashless helpers to be resolved at all, but that is an issue on the ember side of things (i believe).

The resolver merely provides what is asked for.

**Comment by tim-evans** [comment]
That's what I thought. Should I cross post?

**Comment by stefanpenner** [comment]
Yup

**Comment by tim-evans** [comment]
Done :)
