### ISSUE TITLE
confirm @ember as npm scope works

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-resolver#114]
as `@` has meaning already – as a namespace – we should be careful introducing `@` as scope doesn't collide.

A note, we have been throwing the idea, although half baked currently, of `::` as namespace instead.

**Comment by rwjblue** [comment]
I'll try to take a look at this tonight. I vaguely think we should be fine, since `@ember/data` / `@ember/core/component` / etc will not be using the resolver for lookup.

**Comment by Turbo87** [comment]
@rwjblue @stefanpenner what's the state of this? still relevant?
