### ISSUE TITLE
Bower: Unable to find a suitable version for ember-resolver

### ISSUE THREAD

**Issue by avdv** [ember-cli/ember-resolver#119]
```
Unable to find a suitable version for ember-resolver, please choose one:
    1) ember-resolver#~0.1.20 which resolved to 0.1.21 and is required by ember-resolver#2.0.2
    2) ember-resolver#2.0.2 which resolved to 2.0.2 and is required by myproject
```

I also tried 2.0.3 to the same avail.

**Comment by rwjblue** [comment]
ember-resolver 2.x is an NPM package only (it was swapped to be an Ember addon instead of a plain bower package), see https://github.com/aptible/dashboard.aptible.com/pull/423 for the changes needed when updating an Ember CLI project.

**Comment by avdv** [comment]
Thanks, it worked like a charm! :-)
