### ISSUE TITLE
ContainerDebugAdapter.catalogEntriesByType returns objects of wrong type

### ISSUE THREAD

**Issue by gabrielgrant** [ember-cli/ember-resolver#120]
The `ContainerDebugAdapter`'s `catalogEntriesByType()` method matches objects by just [testing whether the type name appears anywhere within the class name](https://github.com/ember-cli/ember-resolver/blob/master/addon/container-debug-adapter.js#L84). The result is that many false-positives are returned.

eg for `model`:

```
var debugAdapter = appInstance.lookup('container-debug-adapter:main');
console.log(debugAdapter.catalogEntriesByType('model'))
```

returns:

```
["ember-data/model", "ember-data/serializers/active-model", "ember-data/adapters/active-model", "ember-cli-test-model-waiter/instance-initializers/test-model-waiter", "ember-cli-test-model-waiter", "hub/ember-cli-test-model-waiter/tests/modules/embe…er/instance-initializers/test-model-waiter.jshint", "hub/instance-initializers/test-model-waiter", "action", "operation", "user", "action.jshint", "operation.jshint", "user.jshint", "action-test", "action-test.jshint", "operation-test", "operation-test.jshint", "user-test", "user-test.jshint", __ember_meta__: Meta]
```

when I'm pretty sure it should just be:

```
["action", "operation", "user"]
```

Not sure how this interacts with pods layouts and the comment in there about different prefixes, but to match "normal" layouts, it seems it should be `exec`ing against something like `RegExp('^[a-zA-Z0-9-_]+\/' + type + '\/(.*)$')`

Note: I originally filed this against ember-cli (for some reason) as ember-cli/ember-cli#5002

**Comment by teddyzeenny** [comment]
Yes. A regexp would be more accurate. Some things to note though. In pods the module name will end with the type so we should modify the regexp to also accept modules that [end with the type name](https://github.com/ember-cli/ember-resolver/blob/6e80b27ca35dfe11aa8de630f4073e4667406de1/addon/container-debug-adapter.js#L9) (like `myapp/company/model.js`). I also don't think we can rely on always having only one word before the type.

The inspector currently uses class detection (`DS.Model.detect`) after getting the list to filter out false positives.

**Comment by stefanpenner** [comment]
as of 3.0 this is now provided by ember (correctly)
