### ISSUE TITLE
How to transpile `index.js` with broccoli-babel-transpiler

### ISSUE THREAD

**Issue by ppcano** [ember-cli/ember-resolver#121]
I am importing  `ember-resolver` in a non ember-cli project.

But I had some problems with the [index.js](https://github.com/ember-cli/ember-resolver/blob/master/addon/index.js) which is using [syntax-export-extensions](http://babeljs.io/docs/plugins/syntax-export-extensions/) to make it work with the [broccoli-babel-transpiler](https://github.com/babel/broccoli-babel-transpiler).

May anybody point me in the direction on how to transpile this syntax with the `broccoli-babel-transpiler` project, I reviewed the `ember-cli` code but I could not find any information.

**Comment by stefanpenner** [comment]
I'm surprised, i think `export { default }` isn't new, but other variations are.

Im not sure how to do this in babel 6, and in babel 5 it "just works"

**Comment by rwjblue** [comment]
Some details in https://github.com/rwjblue/ember-twiddle/commit/3fc82f0875df1e1cb22fd636f1fe93bc450ae107

**Comment by ppcano** [comment]
@stefanpenner you were right, the syntax just works with babel 5.

The problem was that I was using `broccoli-es6-module-transpiler` to convert to AMD modules.

```
  result = babel(result, {
    loose: true
  });
  result = es6Filter(result, {moduleName: function(filePath) {
    return filePath.replace(/.js$/, '');
  }});
```

It works when using @rwjblue example.

```
  result = babel(result, {
    loose: true,
    moduleIds: true,
    modules: 'amdStrict'
  });
```

Thanks to both of you for the help.

**Comment by stefanpenner** [comment]
@ppcano :)
