### ISSUE TITLE
Deprecation warning in Ember 2.2

### ISSUE THREAD

**Issue by jamesdixon** [ember-cli/ember-resolver#124]
Hi,

I installed the Ember CLI addon and removed the Bower package and am now receiving the following deprecation warning:

```DEPRECATION: Usage of `ember/resolver` module is deprecated, please update to `ember-resolver`.```

I'm running Ember 2.2. Any ideas on how to get rid of this?

Thanks!

**Comment by jamesdixon** [comment]
Ah, I think I answered my own question. It looks like a handful of package I use are referencing the addon as `ember/resolver`. I suppose I'll just have to wait for these packages to be updated?

**Comment by rwjblue** [comment]
Take a look at: aptible/dashboard.aptible.com#423 there are a handfull of locations that use `ember/resolver` that need to be updated to `ember-resolver`.

**Comment by jamesdixon** [comment]
@rwjblue thanks! On an unrelated subject, I was just looking at Aptible for one of my clients -- small world!

**Comment by sheriffderek** [comment]
If no add-ons are using the resolver, you can just update them in `app.js` and that will resolve the deprecation notice. `import Resolver from 'ember/resolver';` > `import Resolver from 'ember-resolver';`
