### ISSUE TITLE
ember-data and pod format

### ISSUE THREAD

**Issue by CNDW** [ember-cli/ember-resolver#128]
I love the pod format, it feels much cleaner to define routes/controllers/templates together. However, I feel like ember-data could benefit from a similar structure. I don't think placing the models/adapters/serializers in the same place as the more traditional pods, as the resources are not always tied together in a mutually exclusive format. Would it make sense to add an additional pod format for ember-data related resources to be grouped together?

i.e.
```
app
  |---data
  |       |---user
  |       |      |---adapter.js
  |       |      |---model.js
  |       |      |---serializer.js
  |       |---post
  |              |---adapter.js
  |              |---model.js
  |              |---serializer.js
  |              |---comment
  |                      |---adapter.js
  |                      |---model.js
  |                      |---serializer.js
  |---pods
  |       |---index
  |       |      |---route.js
  |       |      |---controller.js
  |       |      |---template.hbs
  |       |---posts
  |              |---route.js
  |              |---controller.js
  |              |---template.hbs
  |              |---comments
  |                      |---route.js
  |                      |---controller.js
  |                      |---template.js
  |---services
  |       |---...
  |---components
  |       |---...
  |---helpers
  |       |---...
  |---mixins
  |       |---...
```

I haven't seen any updated information on the pod format for a while, so I'm not sure what plans are in store, if any.

**Comment by stefanpenner** [comment]
This is best discussed as an rfc. (Or added to this existing pod rfc)
