### ISSUE TITLE
Re-register failing on `App.reset()`

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-resolver#130]
I don't know if this is an actual issue as I can't seem to reproduce it, but during `App.reset()` I think `container-debug-adapter:main` can still be around in the registry:
https://github.com/ember-cli/ember-resolver/blob/master/app/initializers/container-debug-adapter.js#L9

Which results in an error like this one: https://github.com/emberjs/data/pull/3690/

Is this something we should guard against or is there some other contributing issue on our side resulting in this bug?

**Comment by stefanpenner** [comment]
App.reset is more or less legacy. The idea is to create and destroy app instances

**Comment by NullVoxPopuli** [comment]
I found this issue by trying to solve my 
```
Error: Cannot re-register: `session:main`, as it has already been resolved.
```

problem.

It happens on the third test. :-\
(first test doesn't use the session, though)

![image](https://cloud.githubusercontent.com/assets/199018/15359313/b709d598-1cd6-11e6-89ab-662ab869c892.png)

**Comment by stefanpenner** [comment]
seems to have gone stale?
