### ISSUE TITLE
Use Ember Inflector for pluralization?

### ISSUE THREAD

**Issue by jkeen** [ember-cli/ember-resolver#147]
I'm writing an ember addon that uses the factory pattern. I named the folder with my built-in factories `audio-pledge-factories`, but the resolver does not find the files when I look them up like this: 

```javascript
 getOwner(this).lookup(`audio-pledge@audio-pledge-factory:${dasherizedFactoryName}`);
```
The only way this seems to work is if the folder is named `audio-pledge-factorys`. 😷 

I stepped into the code and it seems like we're not using `Ember.Inflector` for pluralization where it seems like we might want to?

```javascript
pluralize: function(type) {
  return this.pluralizedTypes[type] || (this.pluralizedTypes[type] = type + 's');
},
```

I made a change locally to use `pluralize` on `Ember.Inflector`, and all the tests still pass and it fixes the issue I'm experiencing. I can submit a PR if needed.

But is there another way around this? If this is going through the installed Ember version's resolver, then fixing it from this point on isn't going to help older versions of Ember using this addon.

**Comment by stefanpenner** [comment]
this would be a breaking change, if this is something we want to do it will need to be an ember rfc.

**Comment by rwjblue** [comment]
You can provide `pluralizedTypes` to your resolver
