### ISSUE TITLE
Browserify modules included in `catalogEntriesByType('model')`, which throws error downstream

### ISSUE THREAD

**Issue by ryanlabouve** [ember-cli/ember-resolver#161]
So, quick disclaimer: I'm not 100% sure this is an issue with resolver. This issue is also a little dense to explain clearly, so I'm attaching a PR which may help demonstrate / fix the issue.

When I run `catalogEntriesByType('model')` (specifically from [data_adapter.js#L354](https://github.com/emberjs/ember.js/blob/aeeddf7c00b42a340494465252481b5414d87009/packages/ember-extension-support/lib/data_adapter.js#L354)), browserify modules that have the word "model" in their module definition are included in the returning array.

This is causing a ember.js to throw an error later when it tries to lookup a module like `npm:my/cool/model` via [data_adapter.js#L362](https://github.com/emberjs/ember.js/blob/aeeddf7c00b42a340494465252481b5414d87009/packages/ember-extension-support/lib/data_adapter.js#L362), essentially resulting in something like `getOwner(this)._lookupFactory('model:npm:my/cool/model')` via [this](https://github.com/emberjs/ember.js/blob/aeeddf7c00b42a340494465252481b5414d87009/packages/ember-extension-support/lib/data_adapter.js#L166) which throws `Error message: Invalid Fullname, expected: 'type:name' got: model:npm:prosemirror/dist/model`.

Please note above, the issue is specifically caused by the lookup trying to add `model:` on the the front of the existing package name which makes it violate the naming constraints of a module.

---

In case you are wondering how I ran into this, the `Data` tab on Ember Inspector breaks when we have a NPM package installed via Ember Browserify that has the word "model" in the module definition.

**Comment by igorT** [comment]
@ryanlabouve @rwjblue said the correct approach would be to only lookup modules that start with the `modulePrefix` instead of filtering out `npm`

**Comment by ryanlabouve** [comment]
Sweet! @igorT and I paired to do this. The attached commits have the latest changes.

**Comment by kategengler** [comment]
Closing due to age.
