### ISSUE TITLE
Port on top of @glimmer/di

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-resolver#171]
from https://github.com/emberjs/ember.js/issues/14882:

- [ ] Import `@glimmer/resolver` into ember-resolver.
- [ ] Update resolver to inherit from `@glimmer/resolver`
- [ ] For backwards-compatibility, should delegate to old-style resolver rules if something is looked up and not found
- [ ] Should also export a resolver with Module Unification-only rules (`import Resolver from "ember-resolver/turbo"?`)
- [ ] Release new version on npm

**Comment by Turbo87** [comment]
@tomdale @rwjblue how is "Import `@glimmer/resolver` into ember-resolver" meant? should we add it as an NPM dependency and use e.g. `broccoli-rollup` to import it into the build?

**Comment by mixonic** [comment]
@Turbo87 I believe https://github.com/201-created/dangerously-set-unified-resolver/tree/glimmer-resolver is the latest of this. In #180 I've added feature flags to the resolver. This will make it possible to only include glimmer/di for applications that opt-in to that mode.

**Comment by mixonic** [comment]
This is implemented in 4.1.0 via https://github.com/ember-cli/ember-resolver/pull/182. Let me know if I've missed something!
