### ISSUE TITLE
3 version break ember-inspector.

### ISSUE THREAD

**Issue by johnunclesam** [ember-cli/ember-resolver#175]
Empty Data (model types) list changing from 2.1.1 to 3.0.0.

**Comment by rwjblue** [comment]
Please provide more information. Likely will require a reproduction to understand.

**Comment by stefanpenner** [comment]
I did test, stuff seemed to work. But its possible I missed some important scenario, if you can provide a reproduction we can fix :)

**Comment by johnunclesam** [comment]
![image](https://cloud.githubusercontent.com/assets/21275217/23880519/6c0e9ed8-0854-11e7-9bf2-0105a0a63a31.png)

**Comment by urbany** [comment]
Same thing happened to me.
Data TAB of the inspector is empty on ember-resolver@3.0.0 but is working correctly on v2.1.1

Version info:
```
Ember Inspector	2.0.4
Ember	2.11.3
Ember Data	2.12.0
jQuery	3.1.1
Ember Simple Auth	1.2.0
```

**Comment by stefanpenner** [comment]
I was able to reproduce. Investigating now.

**Comment by urbany** [comment]
It's working on v3.0.1, thanks @rwjblue and @stefanpenner
