### ISSUE TITLE
Leverage babel-plugin-minify-dead-code-elimination

### ISSUE THREAD

**Issue by mixonic** [ember-cli/ember-resolver#181]
#180 introduces https://github.com/chadhietala/babel-plugin-debug-macros for feature flagging. This library will translate feature flags to `true` `false` literals, however it will not strip dead code paths.

This project should strip dead code via https://github.com/babel/babili/tree/master/packages/babel-plugin-minify-dead-code-elimination in a manner similar to @chadhietala's PR to Ember: https://github.com/emberjs/ember.js/pull/15043

**Comment by rwjblue** [comment]
We've removed the feature flagging for MU, so this is no longer an issue.
