### ISSUE TITLE
fallbackCollectionPrefixes should be removed

### ISSUE THREAD

**Issue by mixonic** [ember-cli/ember-resolver#193]
https://github.com/ember-cli/ember-resolver/blob/master/mu-trees/addon/ember-config.js#L34

I don't believe `fallbackCollectionPrefixes` is doing anything. If we need to munge the path before passing it to glimmer resolver (similar to partials) we should do it in glimmer-wrapper.

/cc @dgeb

**Comment by kategengler** [comment]
MU has been removed. Closing.
