### ISSUE TITLE
Add tests for non-app rootNames

### ISSUE THREAD

**Issue by mixonic** [ember-cli/ember-resolver#194]
All tests in https://github.com/ember-cli/ember-resolver/blob/master/mu-trees/tests/unit/resolvers/glimmer-wrapper/basic-test.js either test a relative serialized specifier or an absolute specifier for the main app. Add a test case for a non-app rootName.

**Comment by stefanpenner** [comment]
As module unification is no more, I believe this can be closed. If I am closing this in error please let me know why, and we can reopen.
