### ISSUE TITLE
MU: camelCased lookups

### ISSUE THREAD

**Issue by mixonic** [ember-cli/ember-resolver#195]
Ensure the module unification resolver handles cases where:

```js
export default Component.extend({
  someSession: inject.service()
});
```

Ember looks up `someSession` on the container as camelCase. This means we would require the normalization step for the resolver.

An alternative approach would be to dasherize the property name before calling `lookup` in Ember.

/cc @tmquinn

**Comment by stefanpenner** [comment]
@mixonic I think  in a perfect world, the `serveice()` descriptor would handle that.

**Comment by mixonic** [comment]
Closed in https://github.com/ember-cli/ember-resolver/pull/206

Doing this in Ember's current service injection system is tricky since the injections are part of `metal` but `dasherize` etc are not. I punted and simply implemented in this repo for now.
