### ISSUE TITLE
Component helper usage should warn

### ISSUE THREAD

**Issue by mixonic** [ember-cli/ember-resolver#203]
If an app uses the component helper, it may be passing strings that have `/` in them. Generally the component helper makes it hard to be sure a conversion was successful. The migrator should at least warn for the user to audit usage around those templates with component helpers.

**Comment by rwjblue** [comment]
Did you mean to create this issue in ember-module-migrator?  Are you saying the resolver should warn also?

**Comment by mixonic** [comment]
Opened here in error. Replaced by https://github.com/rwjblue/ember-module-migrator/issues/53
