### ISSUE TITLE
Use shorthands & recursive lookup for component paths called from template

### ISSUE THREAD

**Issue by Leooo** [ember-cli/ember-resolver#217]
in Ruby on Rails there is the nice option to enter the end of a component name in a template, and it will automatically look for components with such names in the folder hierarchy, bubbling until it finds it

so that, instead of using the following in Handlebar (actually Emblem) to call a component added in the pod structure:
```//in authenticated/premises/premise/dashboard/book-engineer/services-account/services-sector-holding/job-type/appointment/faults/template.embl

= authenticated/premises/premise/dashboard/book-engineer/services-account/services-sector-holding/job-type/appointment/faults/priority-question-edit [
  appointment=appointment selectPriority=(route-action "selectPriority") ]
```

We could just use:
```
= priority-question-edit [
  appointment=appointment selectPriority=(route-action "selectPriority") ]
```

and it would still use automatically the `priority-question-edit` located in the same folder as the template (or one of the parent folders)

Just wondering if that's something that has already been considered adding to Ember / Handlebar, and if this could potentially be a new (very useful) feature to add, or it it's actually complicated to add such logic?

**Comment by Leooo** [comment]
(maybe it's in this code as per @locks https://github.com/ember-cli/ember-resolver/blob/master/addon/resolvers/classic/index.js)

**Comment by rwjblue** [comment]
Sounds like you are talking about the local lookup feature that is slated for implementation as part of the module unification efforts (you can [read more here](https://github.com/emberjs/rfcs/blob/master/text/0143-module-unification.md)).

**Comment by Leooo** [comment]
@rwjblue yes that looks like it, thanks for linking. Closing this one.
