### ISSUE TITLE
Support for RFC 297 - Deprecation of Ember.Logger

### ISSUE THREAD

**Issue by lupestro** [ember-cli/ember-resolver#223]
Hi folks - 

RFC 297 will deprecate Ember.Logger, and Ember.Logger will finally go away in Ember 4.0. This project will need a way to support this change when used with Ember 3+, but if this project bridges Ember 2.x and 3.x, support for IE9 in Ember 2.x will require the handling to be more nuanced than in the Ember-3-forward addons. I’m opening this issue so the team can discuss and determine the best way to handle it before proceeding to a change and a PR.

**Comment by lupestro** [comment]
Did the work this morning... pull request is https://github.com/ember-cli/ember-resolver/pull/232

**Comment by rwjblue** [comment]
Thank you!
