### ISSUE TITLE
ember-cli-react/resolver not found

### ISSUE THREAD

**Issue by darlanmendonca** [ember-cli/ember-resolver#231]
I follow the instructions in Readme, and overwrite my app/resolver.js to following:

```js
import Resolver from 'ember-cli-react/resolver';
export default Resolver;
```

But I receive an error, 'Could not find module `ember-cli-react/resolver` imported'

Checking the module `ember-cli-react`, I not found any resolver, directory, or .js file.

any help?

**Comment by rwjblue** [comment]
I'm pretty sure that this repo doesn't say anything about `ember-cli-react`...

**Comment by rwjblue** [comment]
closing due to lack of response, happy to reopen if its still an issue...
