### ISSUE TITLE
emberResolverFeatureFlags() calls project.config() without an environment name

### ISSUE THREAD

**Issue by afn** [ember-cli/ember-resolver#233]
The `config()` function in `ember-cli`'s Project class expects an `env` argument (https://github.com/ember-cli/ember-cli/blob/master/lib/models/project.js#L230-L238) but `emberResolverFeatureFlags()` calls it with no arguments (https://github.com/ember-cli/ember-resolver/blob/master/index.js#L11). This, in turn, causes the app's `config/environment.js` to be invoked with an `undefined` environment.

**Comment by givanse** [comment]
related to https://github.com/ember-cli-deploy/ember-cli-deploy/issues/474
