### ISSUE TITLE
What is Ember Resolver

### ISSUE THREAD

**Issue by davidnewcomb** [ember-cli/ember-resolver#273]
According to your documentation "The ember-resolver is the ember resolver used in ember-cli". Terrific!
I had to do a bit of googling, read a few blog posts by people who have nothing to do with the project and now I think I understand what it is. Well more exactly, I think I know what other people think your project does.

Please can you update your documentation with a section titled "What is Ember Resolver".

I will leave you a link to help:
http://www.bigsoft.co.uk/blog/2010/10/18/the-whats-and-whys-to-creating-project-descriptions

If I knew what it was I'd send you a PR ;)

**Comment by k3n** [comment]
Sadly, this is a systematic problem across many Ember-CLI projects.

Example: https://github.com/ember-cli/ember-load-initializers

**Comment by buschtoens** [comment]
@k3n Can you compile a list of these projects and post it to the `#dev-ember-learning` channel on the [Ember Community Discord](https://discordapp.com/invite/zT3asNS)? This is definitely a problem that we should fix! 💪

**Comment by rwjblue** [comment]
Closed by https://github.com/ember-cli/ember-resolver/pull/376
