### ISSUE TITLE
Module Unification tests are failing and not executed in CI

### ISSUE THREAD

**Issue by buschtoens** [ember-cli/ember-resolver#275]
```
$ EMBER_CLI_MODULE_UNIFICATION=true ember test

....

1..94
# tests 94
# pass  56
# skip  0
# fail  38
```

Were you aware, that the MU tests are not run in CI and are also failing?

I noticed, because I wanted to submit a failing test case for https://github.com/emberjs/ember.js/issues/17217.

**Comment by stefanpenner** [comment]
As module unification is no more, I believe this can be closed. If I am closing this in error please let me know why, and we can reopen.
