### ISSUE TITLE
Models in POD structure

### ISSUE THREAD

**Issue by ryan0x44** [ember-cli/ember-resolver#28]
@rjackson 

The new POD structure (#16) is working really well, however the directory structure becomes a little messy with models, as we use the singular name for models and the plural name for controllers/routes.

For example, say we have a `post` entity, the pod structure would be:
- pods
  - post
    - model.js
  - posts
    - controller.js
    - route.js

But this would be neater:
- pods
  - posts
    - model.js
    - controller.js
    - route.js

Of course one way to achieve this is to override the `resolveModel` method and account for use of the plural, which I'm currently investigating as a solution.

**Comment by Bargs** [comment]
I agree with @eccegordo . I just started using Ember-CLI's pod support and it's very confusing. For now I'm generating the resource and manually copying the model file into the top level models folder. Is that the current best practice? If so I think the generator should be updated.

**Comment by ziflex** [comment]
Hi guys,
is it possible to allow developers to configure this behaviour? Pass some kind of schema or rules?

**Comment by rwjblue** [comment]
Yes, that is built in.

**Comment by aceofspades** [comment]
@ziflex Check out `moduleNameLookupPatterns` in the `Resolver`.

**Comment by decasia** [comment]
I got bitten by this one today, and I notice that the issue has been around for about a year...

Would you folks be willing to accept a PR for the docs to explain what @stefanpenner said, "lets keep models in app for now"? Or maybe even better, a PR for the generator as @Bargs was suggesting?

It seems to me like a note in the documentation would be a good start, even if the plan is to improve this behavior at some future point.

**Comment by sandinmyjoints** [comment]
This has been confusing to me as well. The generator behavior I am seeing matches what @eccegordo mentioned. A plural resource name ("projects") results in two pods being created: 
1. app/pods/project, which holds model.js
2. app/pods/projects, which holds route.js and template.hbs.

Maybe that is intended and good? I supposed you could also create a singular "project" resource, and project vs. projects could be two separate resources that happen to share a model.

But this conflicts with what is stated above in this PR and what people seem to be doing in practice, which is to not have a singular resource at all, and instead of put model.js in app/models.

**Comment by stefanpenner** [comment]
It should be singular

**Comment by sandinmyjoints** [comment]
The resource name should be singular? I can live with that. By default, the route to list projects would be `/project` (instead of `/projects`), right? But it seems like it can be overridden easily enough. Perhaps the docs could mention that resources should be singular, and also show that model.js will be created inside the pod (which is it does currently, and assuming that that is what you intend for it to do).

**Comment by anievagomez** [comment]
![models and other files in a pod directory structure](https://cloud.githubusercontent.com/assets/5857052/6091088/070ac482-ae4f-11e4-8666-780a1163fab1.png)
(*) The conventional pod directory structure
(**)  The collapsed pod directory structure with the ember-model naming convention
(***) The collapsed pod directory structure with the model named after the feature it supports.


![models and other files in a pod directory structure - 2](https://cloud.githubusercontent.com/assets/5857052/6091105/c4e1bb8c-ae4f-11e4-9e7a-aeb7040f7d66.png)

**Comment by stefanpenner** [comment]
> It seems to me like a note in the documentation would be a good start, even if the plan is to improve this behavior at some future point.

pods a still experimental, use them at your own risk until they settle and are documented.

**Comment by stefanpenner** [comment]
First of all, I believe this exploration is needed and is headed down a good path.

some notes:
* extra dots in a file name to mimic folders is a no-go for me
* controllers are no-longer, services + components nicely replace them, so we should think about this in terms of that.
* the "What i want" options, do feel like 2 pods that have been merged. I believe they should be separated

```
features/friend/*
features/friends/* or features/friend-list*
```

* I believe pods, need to be flesh out, but I also believe an additional composition unit is missing. Something that groups pods together. Feature feels to ambiguous, maybe engine/app/bundle ? Basically I in-vision a "slab" of pods + routing, that can be fairly isolated. Loaded/run/tested/developed indepedently but ultimately weaved into the same "single page" experience.

**Comment by Bargs** [comment]
I assumed pods mostly had a one-to-one relationship with the resources defined in the router. So if I have a friends resource, I have a friends pod to match containing all of the code necessary to render the nested routes under that resource.

A common routing pattern is to place a nested route for displaying a single resource under the plural resource definition like this:

```
this.resource('friends', function () {
  this.route('show', {path: ':friend_id'});
});
```

If `friend` and `friends` were split into two separate pods, I would also expect two separate resource definitions.

```
this.resource('friends', function () {
  this.resource('friend', {path: ':friend_id'});
});
```

That might not be a bad thing, since these are typically considered two separate api resources.

**Comment by stefanpenner** [comment]
> A common routing pattern is to place a nested route for displaying a single resource under the plural resource definition like this:

You are correct, the `pod` maps to `route` well, but not well yet a `resource` (or nested route)

**Comment by aceofspades** [comment]
Personally I thought of the module/pod structures as search paths, decoupled from routes. Rather than treat them as unique, what about providing a config with optional lookup functions?

```
var ENV = {
    resolverModules: {
      'app': {},
      'app/pods': {pods: true},
      'app/features': {
        moduleNameLookupPatterns: [
          function(parsedName) {
          }, ...
        ]
      }
    ...
};
```

**Comment by stefanpenner** [comment]
> Personally I thought of the module/pod structures as search paths, decoupled from routes. Rather than treat them as unique, what about providing a config with optional lookup functions?

this is what the resolver does, maybe we should make it more obvious how to subclass it.

**Comment by aceofspades** [comment]
@stefanpenner Augmenting `moduleNameLookupPatterns` is invasive to the stock module and pod trees--each of the functions get called for every lookup. OP could declare his feature tree here without affecting modules/pods and also no wasted lookups. Much less noise in logs too.

**Comment by alexjp** [comment]
I am trying to use pods, and actually liking it ( in the conventional way ).

One thing i am hating though : having the pods/friends and then the pods/components/friends

Something along : pods/routes_and_templates/friends and pods/components/friends 
or 
components/pods/friends

as it is, its a pain the neck in my app :( normal routes and templates all mixed up in the visual tree with components

**Comment by trabus** [comment]
I proposed [Structures](https://github.com/ember-cli/rfcs/pull/5) as a new construct for ember-cli to describe a project structure and inform the resolver how to look up resources in that structure. They're intended to be for internal use by ember-cli, so we're not accidentally introducing hundreds of custom project structures into the community (breaking the conventions and making it difficult to discuss and reason about ember-cli projects).

This thread gave me an idea, that we could use Structures as a way to experiment with different types of pod and slab (or whatever they end up being called) structures (internally through feature flags in .ember-cli), finding a path toward a community standard. The intent was to have multiple structures able to live together, simply informing the resolver how to lookup and blueprint generation how to generate. The other benefit is that they could be used to inform tools how to convert project assets back and forth between different structures (like what I'm trying to do with [ember-cli-podify](https://github.com/trabus/ember-cli-podify)).

**Comment by QuantumInformation** [comment]
Am I supposed to be able to do this in a pod controller:

```js
import Ember from 'ember';

export default Ember.Controller.extend({
  actions: {
    submit: function (firstname, age) {
      this.get("names").push(firstname);
      this.set("totalAge", this.get("totalAge") + age);
    }
  }

});
```

Model:

```js
import DS from 'ember-data';

export default DS.Model.extend({
  names: Ember.A(),
  totalAge: 0
});
```

**Comment by QuantumInformation** [comment]
If I explicitly create a model in the route:
```js
export default Ember.Route.extend({
  model: function () {
    return this.store.createRecord('model')
  },
});
```
it says it can't find the model (its in the pod dir)

**Comment by trabus** [comment]
@QuantumInformation is this a new 0.2.4 app? The podModulePrefix was removed from the default app in 0.2.4 https://github.com/ember-cli/ember-cli/pull/3913

**Comment by QuantumInformation** [comment]
@trabus its a 0.2.5 app

**Comment by trabus** [comment]
@QuantumInformation see https://github.com/ember-cli/ember-cli/issues/4094
You need to add podModulePrefix to your app.js manually now.

**Comment by QuantumInformation** [comment]
thanks @trabus 

Are people mostly nesting pods in a folder like this:   `podModulePrefix: ember-dynamic-forms/pods'`

**Comment by QuantumInformation** [comment]
I think I'll just do this for now

`    podModulePrefix: '',`

**Comment by trabus** [comment]
I'd just comment the line out of your config, but be aware that items will generate in your root folder.

**Comment by QuantumInformation** [comment]
If I comment it out I don't think the models will be resolved relative to the actual pod folder..

**Comment by trabus** [comment]
The resolver tries lookups on several paths for each file. PodModulePrefix just gives it a specific one to use for pods. You have to have it in your app.js to pick it up, your config doesn't get considered unless you tell it to in app.js

**Comment by trabus** [comment]
You can see the paths attempted by setting `ENV.APP.LOG_RESOLVER = true;` in your config.
