### ISSUE TITLE
[MU] Collections: Is it Public unless marked Private?

### ISSUE THREAD

**Issue by gossi** [ember-cli/ember-resolver#281]
The MU RFC mentions public and private collections (ref: https://github.com/emberjs/rfcs/blob/master/text/0143-module-unification.md#module-collections).

I tried private and public collections and put them together in a test project: https://github.com/gossi/sparkles-test/

My expectation from the RFC is, that unless a collection is marked explicitely private it is publicly available. I have created the following file layout:

```
src/ui/components
- sub/
  - -components/
    - cheddar/
      - template.hbs
  - wurst/
    - template.hbs
  - template.hbs
src/ui/routes/application
- template.hbs
```

In my route:

```hbs
{{! src/ui/routes/application/template.hbs }}

<sub/wurst/> {{! no error, but ignored - doesn't show anything }}
<Wurst /> {{! error: Cannot find component wurst }}
<Cheddar /> {{! error: Cannot find component cheddar }}
{{sub/wurst}} {{! error: Specifier must include a rootName, collection, or namespace }}
<Sub /> {{! actually renders src/ui/components/sub/template.hbs }}
```

In the `<Sub />` template:

```hbs
{{! src/ui/components//template.hbs }}

This is <Wurst/> and <Cheddar/>
{{! both components render }}
```

- Both `<Wurst />` and `<Cheddar />` components are rendered from the `<Sub />` component, doesn't matter if they are explicitly put into the private `-components` folder or not.
- Both `<Wurst />` and `<Cheddar />` are **not** rendered in the route template, they are both considered "private"/unresolvable.

For the time being, this behavior is unlogical, because there is no difference in putting such components into a private collection or not. Since MU isn't fully implemented this might be the case.

The question is what _will_ be the final behavior. As noted by me yesterday in discourse (#st-module-unification):
**Use the file structure you want to use and organize your components you want, they are public by default and resolvable by their name unless explicitly marked private with `-components`. Don't create a mapping between fs and invocateable name.**

Can I take that statement for granted? Saying, that in the future and given my example above `<Wurst/>` will publicly available and consumable from, e.g. a route template while the `<Cheddar/>` component will only be available to `<Sub/>` since it is put into private scope.

// cc @nullvoxpopuli @mixonic @dgeb

**Comment by NullVoxPopuli** [comment]
I think there is some ambiguity around what is "Public by default"

Given the currently defined resolution rules:

1. `src/${type}` - typed modules named `main` (explained further below), in
    which default exports match the type specified by the file name.
2. `src/${collection}/${namespace}/${name}/${type}` - expanded collection
    modules, in which default exports match the type specified by the file name.
3. `src/${collection}/${namespace}/${name}` - in which type can be inferred
    based on the module's exports. Default exports must match the default
    type for the collection. If there is no default export, named 

Given that we have some components

```
src
├── ui
│   ├── components
│   │   ├── date-picker
│   │   │   ├── component.js
│   │   │   └── template.hbs
│   │   └── list-paginator
│   │       ├── paginator-control
│   │       │   ├── component.js
│   │       │   └── template.hbs
│   │       ├── component.js
│   │       └── template.hbs
```

and as paths, these all fall under Rule 2:

`src/ui/components/date-picker/{ component.js | template.hbs }`

```
collection: ui/components
namespace: ''
name: date-picker
type: component | template
```

`src/ui/components/list-paginator/{ component.js | template.hbs }`
```
collection: ui/components
namespace: ''
name: list-paginator
type: component | template
```

`src/ui/components/list-paginator/paginator-control/{ component.js | template.hbs }`
```
collection: ui/components
namespace: list-paginator
name: paginator-control
type: component | template
```

So, it's _my_ understanding that anything with a namespace is _not_ public.
Which I think is one of the motivations for the _use_ helper and subsequently the Packages RFC.

**Comment by buschtoens** [comment]
Quoting from [RFC 311](https://github.com/emberjs/rfcs/blob/master/text/0311-angle-bracket-invocation.md):

> Second, while Handlebars technically allows `{{foo/bar}}` as an equivilant
alternative to the `{{foo.bar}}` path lookup (and therefore `foo/bar` is
technically a valid Handlebars path expression), it will not be supported in
angle bracket invocation. This is both because the `/` conflicts with the HTML
closing tag syntax, and the fact that Ember overrides that syntax with a
different semantic.
> 
> In today's semantics, `{{foo/bar}}` does not try to lookup `this.foo.bar` and
invoke it as a component. Instead, it is used as a filesystem scoping syntax.
Since this feature will be rendered unnecessary with [Module Unification](https://github.com/emberjs/rfcs/blob/master/text/0143-module-unification.md),
we recommend apps using "slash components" to migrate to alternatives provided
by Module Unification (or, alternatively, keep using curly invocations for this
purpose).

Quoting from [RFC 143](https://github.com/emberjs/rfcs/blob/master/text/0143-module-unification.md):

> ```
> src
> ├── ui
> │   └── components
> │       ├── date-picker
> │       │   ├── component.js
> │       │   └── template.hbs
> │       └── list-paginator
> │           ├── paginator-control
> │           │   ├── component.js
> │           │   └── template.hbs
> │           ├── component.js
> │           └── template.js
> ├── main.js
> └── router.js
> ```

> From `blogmeister/src/ui/components/list-paginator/template`:
>
> `{{paginator-control}}` resolves to `blogmeister/src/ui/components/list-> paginator/paginator-control/component`
> 
> `{{date-picker}}` resolves to `blogmeister/src/ui/components/date-picker/component`
> 
> `{{power-select}}` resolves to `ember-power-select/src/ui/components/main/component`
> 
> `{{power-select::multiple}}` resolves to `ember-power-select/src/ui/components/multiple/component`

> From `blogmeister/src/routes/posts/post/template`:
> 
> `{{post-viewer}}` resolves to `blogmeister/src/ui/routes/posts/post/-components/post-viewer/component`
> 
> `{{date-picker}}` resolves to `blogmeister/src/ui/components/date-picker/component`
> 
> `{{power-select}}` resolves to `ember-power-select/src/ui/components/main/component`

To me the RFCs are pretty unambiguously about the scoping semantics:

- Nested components are **not** invokable with a path expression.
- A nested component may **only** be invoked by its immediate parent or itself (recursively).
- Top-level components may be invoked from anywhere:
  - route templates
  - other top-level components 
  - arbitrarily nested components
  - ...

So to me, @NullVoxPopuli's assessment is correct. Addon-provided components *must* be top-level components. For grouping purposes, create a new addon for each group.

**Comment by gossi** [comment]
Thanks to all of you.

> I should also add that there's never a reason for a private (e.g. -components) collection within the same parent collection (e.g. components)
nesting components puts them in scope for resolution, just as the private collection would

That's the most important sentence here that "seals the deal". Also @buschtoens summary is pretty straight-forward usable.

I can happily close this issue now, since it is clear.
