### ISSUE TITLE
Local Lookup does not work for addons

### ISSUE THREAD

**Issue by buschtoens** [ember-cli/ember-resolver#296]
Originally reported as https://github.com/emberjs/ember.js/issues/17395.

This code does not account for addons / paths that already have a `rootName`:

https://github.com/ember-cli/ember-resolver/blob/df3ef4e3b327b4cb70badafbe973b4c8c2aa7051/mu-trees/addon/resolvers/glimmer-wrapper/index.js#L96-L109

Specifically, L106 does not anticipate a `source` that looks like:

```
template:addon-local-lookup/src/ui/components/foo/template.hbs
```

**Comment by stefanpenner** [comment]
As module unification is no more, I believe this can be closed. If I am closing this in error please let me know why, and we can reopen.
