### ISSUE TITLE
Classic host app has to use MU resolver to allow local lookups in MU addons

### ISSUE THREAD

**Issue by buschtoens** [ember-cli/ember-resolver#298]
If you want to use an MU addon with local lookup components in a classic host app, the host app _has_ to use the MU resolver. Otherwise there's no `expandLocalLookup`.

https://github.com/ember-cli/ember-resolver/blob/7338be016b1312f41731956573e6bd8a84bcad68/mu-trees/addon/resolvers/glimmer-wrapper/index.js#L86-L127

**Comment by rwjblue** [comment]
Yep, I don't think this is a bug though...

**Comment by stefanpenner** [comment]
As module unification is no more, I believe this can be closed. If I am closing this in error please let me know why, and we can reopen.
