### ISSUE TITLE
Components with templates in pod structure

### ISSUE THREAD

**Issue by rlivsey** [ember-cli/ember-resolver#30]
This might be one for discourse, but wondering how to handle components with templates when in the pod structure (ie not storing them in the templates directory).

At the moment this works, but is a bit weird:

/components/foo-bar.js
/components/foo-bar/template.handlebars

But I'd like something like:

/components/foo-bar/component.js
/components/foo-bar/template.handlebars

or maybe:

/components/foo-bar/index.js
/components/foo-bar/template.handlebars

Is there a way to configure the resolver to handle that / or alternatives?

**Comment by JulianLeviston** [comment]
This is a naming question.

If we have a component called big_combo, which has two files in it... `component.js` and `template.hbs`, the template is obviously called the template, what is the component javascript file called? given that the component is the combination of both the `component.js` and `template.hbs` files? "The component's component file" sounds a bit odd.
