### ISSUE TITLE
Please cut a new release to unblock "Could not find module `ember` imported from `resolver`"

### ISSUE THREAD

**Issue by astronomersiva** [ember-cli/ember-resolver#326]
We are getting the above error in one of our tests after updating Ember from 3.0 to 3.4. I can see that it's already been fixed in #295 but it hasn't been released yet.

A new release would be appreciated!

**Comment by Turbo87** [comment]
why do you think that https://github.com/ember-cli/ember-resolver/pull/295 is related to that error?

**Comment by astronomersiva** [comment]
We have  a test that validates all module exports...We iterate through `require.entries` and require each of them. After updating ember from 3 to 3.4, requiring `resolver` and `ember/resolver` throws the above error.

The test passes on using ember-resolver's master branch(which contains the unreleased changes).

**Comment by Turbo87** [comment]
you have three options:

1. keep using `ember-cli-shims`, like you probably did before, which provides the `ember` module

2. add a blacklist to your `require.entries` test that excludes `resolver` and `ember/resolver`

3. wait for a new major release and then update your app to use it

I'd personally go for 2. until there is a new release.
