### ISSUE TITLE
ember-simple-auth can't resolve 'session' type

### ISSUE THREAD

**Issue by mikkopaderes** [ember-cli/ember-resolver#331]
This is for the module unification environment.

```console
Error while processing route: index Assertion Failed: 'session' is not a recognized type Error: Assertion Failed: 'session' is not a recognized type
```

[This](https://github.com/simplabs/ember-simple-auth/blob/master/addon/initializers/setup-session-restoration.js#L14) is the code that causes the problem. `session:main` is being registered in an initializer [here](https://github.com/simplabs/ember-simple-auth/blob/master/addon/initializers/setup-session.js#L7).

I'm not sure what the problem is but it seems `session:main` isn't being registered properly.

**Comment by rwjblue** [comment]
In MU you need to tweak the config settings, I don't recall the exact incantation ATM but @NullVoxPopuli / @ppcano / @buschtoens likely do...

**Comment by NullVoxPopuli** [comment]
@mikkopaderes you'll want to tweak the config similarly like this: https://github.com/NullVoxPopuli/emberclear/blob/master/packages/frontend/src/resolver.js#L13
I haven't personally used e-s-a, so.. I can't help you with what specifically to add to the config

**Comment by ppcano** [comment]
This comment https://github.com/emberjs/ember.js/issues/17234#issuecomment-461810595 may be useful

**Comment by mikkopaderes** [comment]
@NullVoxPopuli interesting. I didn't know there was a config for that. I actually had to edit the ember-resolver addon itself from inside the `node_modules` folder temporarily. Will try that out..

**Comment by mikkopaderes** [comment]
It works.

```javascript
moduleConfig.types = Object.assign(moduleConfig.types, {
  // ember-simple-auth
  'session': { definitiveCollection: 'session' },
  'session-store': { definitiveCollection: 'session-store' },
});
```

Resolving this..

**Comment by rwjblue** [comment]
Thank you all for helping out! 

We definitely need to get an actual API togeyther that makes this a bit better.
