### ISSUE TITLE
[Module Unification] Allow namespaced specifiers

### ISSUE THREAD

**Issue by buschtoens** [ember-cli/ember-resolver#339]
MU has added namespaces, which allows lookups like:

```js
owner.lookup('service:foo-bar', { namespace: '@npm-scope/my-awesome-addon' });
```

Or injections like:

```js
class ApplicationRoute extends Route {
  @service('@npm-scope/my-awesome-addon::foo-bar') fooBar;
}
```

Would it not make sense to also allow a lookup like this?

```js
owner.lookup('service:@npm-scope/my-awesome-addon::foo-bar');
```

This would make https://github.com/ember-engines/ember-engines/issues/620 a non-issue.

**Comment by stefanpenner** [comment]
As module unification is no more, I believe this can be closed. If I am closing this in error please let me know why, and we can reopen.
