### ISSUE TITLE
Controller (with no corresponding Route) in sub directory cannot be found

### ISSUE THREAD

**Issue by herom** [ember-cli/ember-resolver#37]
I have a controller which is an "orphaned" controller (means: no existing corresponding route) which is called `NotificationCollectionController`. The controller is placed under `app/controllers/notification/collection.js` which seems legit to me (please correct my if I'm wrong) and it cannot be found, causing the following error message if I try to get a grip on it by calling `this.controllerFor` from my `ApplicationRoute`:

> "Assertion Failed: The controller named 'notificationCollection' could not be found. Make sure that this route exists and has already been entered at least once. If you are accessing a controller not associated with a route, make sure the controller class is explicitly defined."

If I rename the file to `notification-collection.js` and move it up a folder, so that it's placed under `app/controllers/notification-collection.js` it is found... is this expected behaviour?

**Comment by abobwhite** [comment]
I am having this problem as well. It may not be resolver related but is this answered somewhere? I am converting my app to ember-cli and seeing this problem and not understanding what the problem is.
