### ISSUE TITLE
5.2.x angle-bracket (with angle-bracket-invocation-polyfill) component issues

### ISSUE THREAD

**Issue by maartenparmentier** [ember-cli/ember-resolver#397]
Since upgrading to the `5.2.x` series we experience issues with angle bracket components (with bracket-invocation-polyfill).

Ember: 3.7.3
Ember-cli: 3.7.1
ember-angle-bracket-invocation-polyfill: 2.0.2

We use PODS

Pre `5.2.x` this used to work:

```hbs
{{#each selectedCategory.filters as |Filter|}}
  <Filter @options={{params}} />
{{/each}}
```

`selectedCategory.filters` can be for example = `['UserFilter', 'DateFilter', 'TemplateFilter']`

These `Filter` components have both a .js and a .hbs file. But since the update the 'actions' specified in the `actions: {}` hash in the .js file can't be found anymore.

e.g. 

```hbs
{{#power-select
	selected=selectedUser
    search=(perform searchUsersTask)
    onchange=(action 'setUser')
    allowClear=true
}}
```

action 'setUser' can not be found.

After trying to update to `5.2.1` the components can't be found at all.

I hope I provided enough information and this issue is opened in the corret repo (and it's not an underlying issue with bracket-invocation-polyfill).

**Comment by rwjblue** [comment]
Hmmm, I don't think we intended for this to work initially. Specifically, you should not have been able to invoke a string in angle brackets like that.

A more simplified example:

```hbs
{{#let 'MyComponent' as |SomeThing|}}
  <SomeThing />
{{/let}}
```

^ should never invoke `MyComponent`.

**Comment by maartenparmentier** [comment]
Oh interesting, thanks for the clarification!

Closing this issue then if it was never intended to work in the first place.
