### ISSUE TITLE
Loading templates doesn't work

### ISSUE THREAD

**Issue by vabatta** [ember-cli/ember-resolver#52]
As of https://github.com/stefanpenner/ember-jj-abrams-resolver/issues/13 this problem is still here.
I have the same issue, when I load into a route that takes some time, any loading templates wouldn't load, but if you do it by URL it works.

**Comment by Sinled** [comment]
It seems loading broken again?

May be i am doing something wrong but it isn't working for me.
here is test app:
https://github.com/Sinled/ember-tests/tree/master/test-loading/app

i have 
```
application.loading
posts.loading
```
templates but none of them are actually loading
```
   Ember      : 1.13.5
   ember-cli  : 1.13.6
```
