### ISSUE TITLE
ERROR: You're not allowed to have more than one controller property map to the same query param key

### ISSUE THREAD

**Issue by fran-worley** [ember-cli/ember-resolver#589]
The PR here #588 seems to have unintended consequences with controller query params. 

Since upgrading to v8.0.1 we're seeing this error: 

> ERROR: Uncaught Error: Assertion Failed: You attempted to generate a link for the "tasks" route, but did not pass the models required for generating its dynamic segments. Assertion Failed: You're not allowed to have more than one controller property map to the same query param key, but both `tasks:dueStatus` and `tasks.index:dueStatus` map to `due-status`. You can fix this by mapping one of the controller properties to a different query param key via the `as` config option, e.g. `dueStatus: { as: 'other-dueStatus' }`

For reference our controller def looks like this:
```
import Controller from '@ember/controller';

export default Controller.extend({
  queryParams: {
    dueStatus: "due-status"
  },
  dueStatus: null
});
```

**Comment by rwjblue** [comment]
Hmmm sorry about that @fran-worley, but thank you for reporting!

 I'm trying to figure out why that would have caused the issue you are seeing. Anything special about your setup? Is there a file at `app/tasks/index.js`? Are you using `pods` (with or without a `podModulePrefix`)? Where on disk is that controller that you expect to get resolved?

**Comment by fran-worley** [comment]
Nope - we've got nothing weird like that going on. I even ran a find and replace for `due-status` and that is the only file where it is mentioned.

I've reverted back to v8.0.0 and it's fixed the issue. We're on ember-source v3.20.3 just incase that is of relevance.

**Comment by Turbo87** [comment]
@rwjblue if you need a reproduction, https://github.com/skylines-project/skylines/pull/2119 is showing a similar issue

**Comment by rwjblue** [comment]
Ya I'll revert and re-release once I'm back to my computer. Then I can dig in without folks being affected...
