### ISSUE TITLE
may the initializers.js be modularized?

### ISSUE THREAD

**Issue by ppcano** [ember-cli/ember-resolver#67]
Importing the `dist/ember-resolver.js` library fails because the [initializers.js](https://github.com/stefanpenner/ember-resolver/blob/master/packages/ember-resolver/lib/initializers.js) is self executed when `Ember.Application` is not yet accesible.

We are not using ember-cli, so I do not know if the initializer may be modularized to be used when necessary.

**Comment by lancedikson** [comment]
I have the same issue: #94. @ppcano, do you have a success with modularized initializers.js?

**Comment by stefanpenner** [comment]
just be sure this file is loaded after ember, but before the app. I believe this is a fine requirement. 
 
i dont see how that following will really helper:
```js
Ember.onLoad('Ember.Application', function(Application) {
  Application.initializer({
```

As if Ember is present, Ember.Application should also be present.

**Comment by lancedikson** [comment]
@stefanpenner, sorry for annoying, but I have a problem. My project's backend is RoR. I don't use Assets Pipeline, 'cause it sucks and build assets with Gulp. I used Ember 1.9 in project and now I decide upgrade it to 1.12 and new resolver with ES6-modules. I used Require.js as scripts loader and wanna use it in the future.
So, I installed new Ember and resolver, but I have an issue with resolver:
![2015-05-20 22-40-18 sun](https://cloud.githubusercontent.com/assets/1955931/7734790/49ec2622-ff41-11e4-8f00-6649ff01ba37.png)
And I sure, that it loads after the Ember:
![2015-05-20 22-41-48 sunsay](https://cloud.githubusercontent.com/assets/1955931/7734804/753de18a-ff41-11e4-894f-ec10c6074b9f.png)

Could you help me, please? What may be a reason of the error? Maybe it needs some wrapper for Require.js? I don't undestand.

**Comment by lancedikson** [comment]
@stefanpenner, tell me please, is resolver depends on load-initializer? Or not? Just I have issues with it too.

**Comment by lancedikson** [comment]
@stefanpenner, can you help me, please?

**Comment by stefanpenner** [comment]
@lancedikson I really have no idea what the issue is you are facing as the resolver and initializer have nothing to do with each other.

**Comment by lancedikson** [comment]
@stefanpenner, ok. Thanks for the answer.
