### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by ziflex** [ember-cli/ember-resolver#78]
Hi guys,
for some reasons, I can't use Ember-CLI, but I'd like to use this part of it. 
Unfortunately, I discovered that 'ember-resolver' doesn't follow AMD fully - it uses Ember's global variable instead of requiring it as dependency.
Is it possible to provide additional version with full AMD support ?

**Comment by stefanpenner** [comment]
I would like ember-cli to fully support AMD, unfortunately this repo has nothing to do with it.

**Comment by stefanpenner** [comment]
the effort relies on work in these repos:

* https://github.com/ember-cli/loader.js
* github.com/stefanpenner/petal

@abuiles has been making some progress on this front.
