### ISSUE TITLE
Colocating the model with templates, controllers, partials and routes in a pod directory structure

### ISSUE THREAD

**Issue by anievagomez** [ember-cli/ember-resolver#81]
I need to colocate the model with the routes, controllers, templates and partials in a pod-structure (see image).
![screen shot 2015-01-28 at 1 03 29 pm](https://cloud.githubusercontent.com/assets/5857052/5947510/8aebd70a-a6f2-11e4-891c-b294556e3911.png)

(I have posted this also at: "Organize your ember with pods"http://cball.me/organize-your-ember-app-with-pods/       and at "ember-magic-resolver"https://github.com/bintoro/ember-magic-resolver)

How can I make this possible?

**Comment by stefanpenner** [comment]
subclass the resolver, and override `resolverController`
