### ISSUE TITLE
How are the needs supposed to be specified for a controller with nested routes?

### ISSUE THREAD

**Issue by gonvaled** [ember-cli/ember-resolver#85]
I was doing:

```
needs : [ 'servicesIndex' ]
```

This was working long ago. Now I have moved to ember-cli, and I got some errors, so while refactoring I renamed my controller (I thought this was right) services/index.js -> services-index.js

But now (after a big refactoring) I realize that ember is (silently unless enabled) creating a new controller, and not using mine! It seems it is indeed looking for services/index.js

So it seems that the refactoring that I should have done is in the needs, changing to:

```
needs : [ 'services/index']
```

and not renaming the files.

Is this correct? Why has this changed for ember-cli? Is this documented somewhere? I am not able to find anything related needs for nested resources in the ember changelog (https://github.com/emberjs/ember.js/blob/master/CHANGELOG.md)

**Comment by stefanpenner** [comment]
It should be identical to whats on disk. So a slash
