### ISSUE TITLE
Nested pods & Adapters

### ISSUE THREAD

**Issue by david-duncan** [ember-cli/ember-resolver#91]
Trying to fully utilize pod structure to make stuff cleaner. We would prefer to have nested directories in pods per our services, and we encountered some oddities with adapters.

Structure

    pods/service-a/device/model.js

Can't resolve the adapter from inside of

    pods/service-a/device/adapter.js

But it can resolve the adapter from inside of

    app/adapters/service-a/device.js

Anything we are doing wrong? Anything we can do to override so that we can keep everything in pods? Is this not the ember way at all?

**Comment by stefanpenner** [comment]
we will be doing a thorough massage of the pod layout in the next few weeks.

**Comment by david-duncan** [comment]
awesome can't wait to read about it. sorry if this was in the wrong repo

**Comment by stefanpenner** [comment]
> awesome can't wait to read about it. sorry if this was in the wrong repo

nope the right repo, but its absolutely on our minds. Im just doing issue house keeping.
