### ISSUE TITLE
Convert to v2 add-on format

### ISSUE THREAD

**Issue by SergeAstapov** [ember-cli/ember-resolver#921]
Looks like this add-on is great candidate for v2 add-on format aka Embroider native conversion.

@kategengler I see you started working on v11 - do you think we could e.g. add ember-auto-import@2 as a dependency as part of v11 release so we don't need another major version bump for the actual conversion to v2 format?

**Comment by SergeAstapov** [comment]
> There are some major changes queued up

noted, looking forward to see those.

Will close for now

**Comment by kategengler** [comment]
Sorry maybe I wasn't clear -- those changes are already on master, so the PR should be fine. There's also #852 which does convert to v2, I think.
