### ISSUE TITLE
Deprecated Computed Syntax

### ISSUE THREAD

**Issue by daltones** [ember-cli/ember-resolver#93]
Here:
https://github.com/ember-cli/ember-resolver/blob/master/packages/ember-resolver/lib/core.js#L228-L235

Should ember-resolver have a new breaking compatibility release with Ember 1.11 to solve deprecation in 1.12?

**Comment by rwjblue** [comment]
That is a getter only, and is not deprecated.

**Comment by akshayrawat** [comment]
Confirm. This issue can be closed.
