### ISSUE TITLE
Error with lookup process

### ISSUE THREAD

**Issue by lancedikson** [ember-cli/ember-resolver#94]
Hi, I have project with Ember 1.9 and I try to upgrade it upon Ember 1.12 with new resolver. Its build process depends on gulp.js. I rewrite all to ES6 modules and include new resolver:

```
import Ember from 'ember';
import Resolver from 'ember/resolver';
import loadInitializers from 'ember/load-initializers';

var Sun = Ember.Application.create({
    LOG_ACTIVE_GENERATION: true,
    LOG_VIEW_LOOKUPS: true,
    applicationName: "SunSay",
    firstRun: true,
    modulePrefix: 'sun',
    Resolver: Resolver
});

loadInitializers(Sun, 'sun');

export default Sun;
```

So, but I have some issues with loading app:
![2015-05-18 00-09-44 screenshot](https://cloud.githubusercontent.com/assets/1955931/7672215/998ee814-fcf2-11e4-9e65-e69eada90e53.png)
![2015-05-18 00-09-16 screenshot](https://cloud.githubusercontent.com/assets/1955931/7672217/9eed68f8-fcf2-11e4-971c-848834e66b6c.png)

Do you have any ideas what may be a reason for exception?

**Comment by stefanpenner** [comment]
> . Its build process depends on gulp.js.

if you use ember-cli, you would already be productively working on your product not the build tooling :trollface:

**Comment by stefanpenner** [comment]
> Do you have any ideas what may be a reason for exception?

Some dependency is likely out-of-sync, please go review what ember-cli's dependencies are in this case.
