### ISSUE TITLE
Change usages of `Ember.create` and `Ember.keys` to `Object.create` and `Object.keys`

### ISSUE THREAD

**Issue by akshayrawat** [ember-cli/ember-resolver#97]
This leads to a lot of deprecation noise when working with Ember 1.13.2.

Happy to submit a PR if this is legit.

**Comment by stefanpenner** [comment]
We do want to switch, but this library needs to continue to work for 1.13.2 users who use ie8.

I guess Let's inline the two polyfills here

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-resolver/pull/100
