### ISSUE TITLE
ReadMe is missing on npm since v9

### ISSUE THREAD

**Issue by mkszepp** [ember-cli/ember-resolver#975]
It looks like the readme will not anymore deployed on npm since version v9

https://www.npmjs.com/package/ember-resolver

**Comment by mkszepp** [comment]
@NullVoxPopuli looks like it wasn't fixed with merged PR

**Comment by NullVoxPopuli** [comment]
I'm no release-it expert, but it was worth a shot.
maybe a prepare script would be better?
