### ISSUE TITLE
[v13] reopen is not a function

### ISSUE THREAD

**Issue by mkszepp** [ember-cli/ember-resolver#984]
In v13 ember-resolver was converted to native class.

This is causing error `Uncaught TypeError: ember_resolver__WEBPACK_IMPORTED_MODULE_1__.default.reopen is not a function` when we use [ember-can](https://github.com/minutebase/ember-can).
It was used inside addon [see here](https://github.com/minutebase/ember-can/blob/7a58baa3aa7d8fd9dfdf98fdfe08efde2b468354/ember-can/src/initializers/setup-ember-can.js#L3)

Is there planned to readd this function like it was done for `create`?

**Comment by NullVoxPopuli** [comment]
ember-can should probably extend the class or provide a decorator. reopen is non a great pattern 😅

**Comment by mkszepp** [comment]
Okay thanks! We will fix it in ember-can
